## Data structure conversion
Create a dictionary which maps product names to prices, using the `price_table` given below.

In [1]:
price_table = [("honey", 2.45), ("butter", 1.30), ("catfood", 4.85), ("tea", 1.50)]

# your code goes here:

ingredients_list = {}
for ingredients_and_prices in price_table:
    ingredients_list[ingredients_and_prices[0]] = ingredients_and_prices[1]

print(ingredients_list)


# Alternative 1 with iterator unpacking in the for loop:
ingredients_list = {}
for ingredient, price in price_table:
    ingredients_list[ingredient] = price

print(ingredients_list)

# Alternative 2 with dict casting (probably "best" solution here):
ingredients_list = dict(price_table)

print(ingredients_list)

{'honey': 2.45, 'butter': 1.3, 'catfood': 4.85, 'tea': 1.5}
{'honey': 2.45, 'butter': 1.3, 'catfood': 4.85, 'tea': 1.5}
{'honey': 2.45, 'butter': 1.3, 'catfood': 4.85, 'tea': 1.5}


## Nested data structures
The data below is given as a list of nested tuples, where each outer tuple is structured as follows:

`(<name>, (<price>, <amount>))`

Transform the data into a more explicit form, a dictionary where each key is a product name and each value is again a dictionary containing entries for `"price"` and `"amount"`. The result should look like this:
```python
{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 100}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}
```

In [2]:
input_data = [
    ("honey", (2.45, 10)), 
    ("butter", (1.30, 100)), 
    ("catfood", (4.85, 3)), 
    ("tea", (1.50, 123)),
]

# your code goes here:
recipe = {}
for ingredient_info in input_data:
    recipe[ingredient_info[0]] = {"price": ingredient_info[1][0], "amount": ingredient_info[1][1]}

print(recipe)

# Alternative 1 with iterator unpacking in the for loop (probably "best" solution here):
recipe = {}
for ingredient, (price, amount) in input_data:
    recipe[ingredient] = {"price": price, "amount": amount}

print(recipe)

# Alternative 2 with dict comprehension
recipe = dict((ingredient, {"price": price, "amount": amount}) for ingredient, (price, amount) in input_data)

print(recipe)

{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 100}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}
{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 100}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}
{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 100}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}


Finally, reduce the amount of butter by `20` and print the entire dictionary:

In [3]:
# your code goes here:
print(recipe)
recipe["butter"]["amount"] -= 20
print(recipe)

{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 100}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}
{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 80}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}


## Find minimum

Find the smallest number in the list below using a `for`-loop and an `if`-condition!

In [4]:
numbers = [27, 83, 20, 77, 1923, 4, 7, 19]

# your code goes here:
current_min = numbers[0] 
for number in numbers:
    if number < current_min:
        current_min = number
print(current_min)

4


# Functions

## Basic Function
Write a function `my_contact_information` which takes **no** arguments and prints your contact information as follows:

```
First Name: <Your first name>
Last Name: <Your last name>
Email: <Your email>
```

In [5]:
# your code goes here:

def my_contact_information():
    print("First Name: Moritz")
    print("Last Name: Erlacher")
    print("Email: moritz.erlacher@student.tugraz.at")

my_contact_information()

First Name: Moritz
Last Name: Erlacher
Email: moritz.erlacher@student.tugraz.at



## Functions and return
Calculate the sum of a list. Write a function which takes a list or a tuple as input. Calculate the sum of the elements in the list/tuple and return the resulting sum.  
*Do not use `sum()`*

**Example:**  
```
[1,2,3] -> 6
(6, 90, 10, 15, 114, 25, 18, 91, 51) -> 420
[63, 100, 48, 79, 4, 85, 26, 84, 16, 73, 58, 78, 87, 198, 321, 17] -> 1337
```

In [6]:
# Your code goes here.
def sum_of_numbers(numbers):
    result = 0
    for number in numbers:
        result = result + number
    return result

result_of_sum = sum_of_numbers([1,2,3,4,5])
print(result_of_sum)


15


## Functions with keyword arguments
Write a function which takes a list or a tuple of numbers and a keyword argumnet `power` which default value is 2. For each number you should calculate the number to the power (given by the keyword argument). Return the new list.

**Example: with power=2**  
```
[1,2,3] -> [1, 4, 9]
(6, 90, 10, 15, 114, 25, 18, 91, 51) -> [36, 8100, 100, 225, 12996, 625, 324, 8281, 2601]
```
**Example: with power=3**  
```
[63, 100, 48, 79] -> [250047, 1000000, 110592, 493039]
```

In [7]:
# Your code goes here.
def power_of_numbers(numbers, power = 2):
    numbers_to_power = []
    for number in numbers:
        numbers_to_power.append(number**power)
    return numbers_to_power

print(power_of_numbers([63, 100, 48, 79]))
print(power_of_numbers([63, 100, 48, 79], power = 3))

# Alternative with listcomprehension
def power_of_numbers(numbers, power = 2):
    return [number**power for number in numbers]

print(power_of_numbers([63, 100, 48, 79]))
print(power_of_numbers([63, 100, 48, 79], power = 3))
    

[3969, 10000, 2304, 6241]
[250047, 1000000, 110592, 493039]
[3969, 10000, 2304, 6241]
[250047, 1000000, 110592, 493039]


# File I/O

## Cookbook
You want to use a cookbook to calculate amounts for any desired number of servings. For this your have following information:
* filename of the recipe (`string`), e.g. `"bananabread.recipe"`
* name of the desired recipe (`string`), e.g. `"Bananabread"`
* `servings` -> number of servings (`int`), e.g. 3 <br>  

The `.recipe`-file contains the desired recipe. From there, read the instructions and ingredients, calculate the needed amounts given by the servings and save them in a new file.  
Such a `.recipe` file could look like this:
```
Mix everything together and bake for 45min at 180°C.
Wheat,180,g
Sugar,100,g
Cocoa,60,g
Salt,1,pinch
Baking Powder,1,tsp
Chopped Chocolate,170,g
Bananas,3,psc
```
The first line denotes always the instructoins and all following lines contains the ingredients. All ingreadients have the following structure:  
`<Name of Ingredient>,<amount>,<unit>`.

Now read all Ingredients and multiply the amount by the number of servings. Sace the final new recipe in a new `.txt` file with the same filename as the `.recipe` file (but with `.txt` as suffix).  
The file should look like the following:
```
How to make 3 serving(s) of Bananabread:
Wheat: 540g
Sugar: 300g
Cocoa: 180g
Salt: 3pinch
Baking Powder: 3tsp
Chopped Chocolate: 510g
Bananas: 9pcs
Oil: 180ml
Mix everything together and bake for 45min at 180°C.
```

In [8]:
# Your code goes here:
def multiply_ingredients_of_recipe(filename, recipe_name, servings):
    with open(filename, "r") as recipe_file, open(filename.replace(".recipe", ".txt"), "w") as adjusted_recipe_file: # open both files in same with statement. For the writing file replace .recipe with .txt
        content_of_recipe_file = recipe_file.readlines()
        recipe = content_of_recipe_file[0] # First line of the reading file is the recipe
        adjusted_recipe_file.write(f"How to make {servings} serving(s) of {recipe_name}\n") # Write the first line for the file
        for line in content_of_recipe_file[1:]: # start at index 1
            ingredient, amount, unit = line.strip().split(",") # Strip the line for \n removal and split at ",". Unpack it in the three parts ingredient, amount, unit
            adjusted_recipe_file.write(f"{ingredient}: {int(amount)*servings}{unit}\n") # Create the necessary line and write it to the file, don't forget the \n
        adjusted_recipe_file.write(recipe.strip()) # .strip() since we don't want a newline at the end

multiply_ingredients_of_recipe("bananabread.recipe", "Bananabread", 3)